# Transient db - will lose it's data once restarted
version: "3"
services:
  postgres:
    image: postgres:10
    container_name: psql
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prisma
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d/
