[lib]
name = "prisma"
crate-type = ["dylib", "staticlib"]
path = "src/lib.rs"

[[bin]]
name = "prisma-server"
path = "src/main.rs"

[package]
name = "prisma"
version = "0.1.0"
authors = ["Dominic Petrick <petrick@prisma.io>", "Julius de Bruijn <bruijn@prisma.io>"]
edition = "2018"

[dependencies]
prost = "0.4"
prost-derive = "0.4"
prost-types = "0.4"
bytes = "0.4"
lazy_static = "1.2"
r2d2 = "0.8"
r2d2_sqlite = "0.8"
rusqlite = { version = "0.16", features = ["chrono"] }
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
serde_json = "1.0"
url = "1.7"
url_serde = "0.2"
chrono = { version = "0.4", features = ["serde"] }
uuid = "0.7"
arc-swap = "0.3"

[build-dependencies]
prost-build = "0.4"
