[lib]
crate-type = ["dylib", "staticlib"]

[package]
name = "prisma"
version = "0.1.0"
authors = ["Dominic Petrick <petrick@prisma.io>", "Julius de Bruijn <bruijn@prisma.io>"]
edition = "2018"

[dependencies]
prost = "0.4"
prost-derive = "0.4"
prost-types = "0.4"
bytes = "0.4"
lazy_static = "1.2"
r2d2 = "0.8"
r2d2_sqlite = "0.8"
rusqlite = { version = "0.16", features = ["chrono"] }
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
serde_json = "1.0"
url = "1.7"
url_serde = "0.2"
chrono = { version = "0.4", features = ["serde"] }
uuid = "0.7"
arc-swap = "0.3"
log = "0.4"
env_logger = "0.6"
sql = { git = "https://github.com/prisma/sql.git", branch = "master" }
debug_stub_derive = "0.3"
once_cell = "0.1"

[build-dependencies]
prost-build = "0.4"
