[workspace]
members = [
  "prisma-models",
  "migration-engine/connectors/migration-connector",
  # "migration-engine/connectors/sql-connector",
  "migration-engine/core",
  "query-engine/connectors/connector",
  "query-engine/connectors/sql-connector",
  "query-engine/prisma",
  "query-engine/native-bridge",
  "query-engine/core",
  "libs/prisma-datamodel",
]
