[package]
name = "sql-migration-connector"
version = "0.1.0"
authors = ["Marcus BoÌˆhm <boehm@prisma.io>"]
edition = "2018"

[dependencies]
migration-connector = { path = "../migration-connector" }
datamodel = { path = "../../../libs/datamodel" }
chrono = { version = "0.4" }
prisma-query = { path = "../../../libs/prisma-query" }
serde_json = "1.0"
rusqlite = { version = "0.16", features = ["chrono", "bundled"] }
barrel = { version = "0.5.3", features = ["sqlite3"] }
itertools = "0.8"
