jobs:

  # CLI testing
  cli:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: cd cli && yarn
      - run: cd cli && yarn test
      - run: env

  # content deployment
  content:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: sudo npm i -g @graphcool/docs-cli
      - run:
          command: .circleci/deploy-docs.sh
          environment:
            BLUE_ID: cjce1hjzi0z1o01539nc8949x
            GREEN_ID: cjce1bhux0xwx0127k0ava9o4
            ALIAS: prisma-docs

workflows:
  version: 2
  build:
    jobs:
      - cli:
          filters:
            branches:
              only:
                - master
#      - content:
#          filters:
#            branches:
#              only:
#                - master
