version: "3"
services:
  app:
    image: graphcool/scala-sbt-docker
    environment:
      CLUSTER_VERSION: "latest"
      COMMIT_SHA: "123abcd"
      PACKAGECLOUD_PW: "${PACKAGECLOUD_PW}"
      PRISMA_CONFIG: |
        port: 4466
        rabbitUri: amqp://rabbit
        databases:
          default:
            connector: mysql
            migrations: true
            host: test-db
            port: 3306
            user: root
            password: prisma
            rawAccess: true
    volumes:
      - ../../../..:/root
      - ~/.ivy2:/root/.ivy2
      - ~/.coursier:/root/.coursier
    working_dir: /root/server
    networks:
      - tests

  test-db:
    image: mysql:5.7
    command: mysqld
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
      - "3306"
    networks:
      - tests
    tmpfs: /var/lib/mysql

  rabbit:
    image: rabbitmq:3.7.2-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - tests

networks:
  tests: