version: "3"
services:
  app:
    image: graphcool/scala-sbt-docker
    environment:
      CLUSTER_VERSION: "latest"
      COMMIT_SHA: "123abcd"
      PACKAGECLOUD_PW: "${PACKAGECLOUD_PW}"
      PRISMA_CONFIG: |
        port: 4466
        rabbitUri: amqp://rabbit
        databases:
          default:
            connector: mongo
            uri: mongodb://prisma:prisma@test-db:27017/?authSource=admin&ssl=false

    volumes:
      - ../../../..:/root
      - ~/.ivy2:/root/.ivy2
      - ~/.coursier:/root/.coursier
    working_dir: /root/server
    networks:
      - tests

  test-db:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - "27017"
    networks:
      - tests

  rabbit:
    image: rabbitmq:3.7.2-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - tests

networks:
  tests: