[package]
name = "connector"
version = "0.1.0"
authors = []
edition = "2018"

[features]
default = ["sql", "sqlite"]
sqlite = ["rusqlite", "libsqlite3-sys", "r2d2_sqlite"]
sql = ["r2d2"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "0.1"
prisma-query = { git = "https://github.com/prisma/prisma-query.git" }
prisma-models = { path = "../../../prisma-models" }
prisma-common = { path = "../../../libs/prisma-common" }
failure = "0.1"
failure_derive = "0.1"
uuid = "0.7"

r2d2 = { version = "0.8", optional = true }
r2d2_sqlite = { version = "0.8", optional = true }
rusqlite = { version = "0.16", features = ["chrono", "bundled"], optional = true }
libsqlite3-sys = { version = "0.11", optional = true }
