[package]
name = "migration-core"
version = "0.1.0"
authors = ["Marcus BoÌˆhm <boehm@prisma.io>"]
edition = "2018"

[dependencies]
migration-connector = { path = "../connectors/migration-connector" }
nullable = { path = "../../libs/nullable" }
database-inspector = { path = "../../libs/database-inspector" }
datamodel = { path = "../../libs/datamodel" }
prisma-models = { path = "../../prisma-models" }
chrono = { version = "0.4", features = ["serde"] }
jsonrpc-core = "10.1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
boolinator = "2.4.0"

[dev-dependencies]
sql-migration-connector = { path = "../connectors/sql-migration-connector" }

[[bin]]
name = "migration-engine-rpc"
path = "src/bin/rpc_api_bin.rs"

[[bin]]
name = "suggest-migrations"
path = "src/bin/suggest_migrations.rs"
