version: "3"
services:
  app:
    image: prismagraphql/build-image:debian
    environment:
      CLUSTER_VERSION: "latest"
      COMMIT_SHA: "123abcd"
      PACKAGECLOUD_PW: "${PACKAGECLOUD_PW}"
      RABBITMQ_URI: amqp://rabbit
      PRISMA_CONFIG: |
        port: 4466
        rabbitUri: amqp://rabbit
        databases:
          default:
            connector: postgres
            migrations: true
            host: test-db
            port: 5432
            user: postgres
            password: prisma
            rawAccess: true
    volumes:
      - ../..:/root/build
      - ~/.ivy2:/root/.ivy2
      - ~/.coursier:/root/.coursier
    working_dir: /root/build
    networks:
      - tests

  test-db:
    image: postgres:10.3
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: "prisma"
      PGDATA: "/pgtmpfs"
    ports:
      - "5432"
    networks:
      - tests
    tmpfs: /pgtmpfs

  rabbit:
    image: rabbitmq:3.7.2-management
    restart: always
    hostname: rabbit-host
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - tests

networks: tests:
