[package]
name = "core"
version = "0.1.0"
authors = ["Dominic Petrick <dompetrick@gmail.com>"]
edition = "2018"

[dependencies]
graphql-parser = "0.2.2"
prisma-models = { path = "../../prisma-models" }
connector = { path = "../connectors/connector" }
failure = "0.1"
failure_derive = "0.1"
Inflector = "0.11"
lazy_static = "1.3"